# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://keepintracks/"
title: KeepinTracks
copyright: "© KeepinTracks 2024"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "personal favorites", "things"]

# minify:
#   disableXML: true
#   # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON