############################
## CHANGE THESE
############################

baseURL: 'https://www.keepintracks.com/'
title: "Keepin' Tracks"

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


