############################
## CHANGE THESE
############################

baseURL: 'https://keepintracks.com'
title: "Keepin' Tracks"

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


