############################
## CHANGE THESE
############################

baseURL: 'https://SimpleOpenSource.github.io/KeepinTracks'
title: KeepinTracks

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


