############################
## Author
############################

author:
  name: Keepin' Tracks
  image: logo.png
  greeting: "Providing tools to easily track and use your data!"
  icon: ""

############################
## Links
############################

links:
  - youtube: https://www.youtube.com/@KeepinTracks
  - email: mailto:info@keepintracks.com
  # - github: https://github.com/SimpleOpenSource/KeepinTracks
  # - link: https://github.com/SimpleOpenSource/KeepinTracks#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: KeepinTracks
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
