env: production # to enable google analytics, opengraph, twitter-cards and schema.
# description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
# author: Theme PaperMod
author: ["KeepinTracks"] # multiple authors
customCSS: ["css/custom.css"]

assets:
    favicon: "/favicons/favicon.ico"
    favicon16x16: "/favicons/favicon-96x96.png" 
    favicon32x32: "/favicons/favicon-96x96.png" 
    webmanifest: "/favicons/site.webmanifest"
    apple_touch_icon: "/favicons/apple-touch-icon.png"

defaultTheme: auto
# disableThemeToggle: true
ShowShareButtons: true
ShowReadingTime: true
# disableSpecial1stPost: true
# displayFullLangName: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
# ShowRssButtonInSectionTermList: true
ShowAllPagesInArchive: true
ShowPageNums: true
ShowToc: true
# comments: false
# images: ["images/papermod-cover.png"]

# profileMode:
#   enabled: false
#   title: PaperMod
#   imageUrl: "#"
#   imageTitle: my image
#   # imageWidth: 120
#   # imageHeight: 120
#   buttons:
#     - name: Archives
#       url: archives
#     - name: Tags
#       url: tags

homeInfoParams:
  Title: "Hi."
  Content: >
    This ain't AI. This is me.

socialIcons:
  - name: "substack"
    url: "https://keepintracks.substack.com/"


#   # analytics:
#   #     google:
#   #         SiteVerificationTag: "XYZabc"

#   assets:
#     disableHLJS: true
#   #     favicon: "<link / abs url>"
#   #     favicon16x16: "<link / abs url>"
#   #     favicon32x32: "<link / abs url>"
#   #     apple_touch_icon: "<link / abs url>"
#   #     safari_pinned_tab: "<link / abs url>"

#   # cover:
#   #     hidden: true # hide everywhere but not in structured data
#   #     hiddenInList: true # hide on list pages and home
#   #     hiddenInSingle: true # hide on single page

#   # fuseOpts:
#   #     isCaseSensitive: false
#   #     shouldSort: true
#   #     location: 0
#   #     distance: 1000
#   #     threshold: 0.4
#   #     minMatchCharLength: 0
#   #     keys: ["title", "permalink", "summary", "content"]

# markup:
#   goldmark:
#     renderer:
#       unsafe: true
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai

# # privacy:
# #   vimeo:
# #     disabled: false
# #     simple: true

# #   twitter:
# #     disabled: false
# #     enableDNT: true
# #     simple: true

# #   instagram:
# #     disabled: false
# #     simple: true

# #   youtube:
# #     disabled: false
# #     privacyEnhanced: true

# services:
#   instagram:
#     disableInlineCSS: true
#   twitter:
#     disableInlineCSS: true